config/routes.rb
Survey::Application.routes.draw do
  get "sessions/new"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions
  resources :enquetes do
    resources :responses
  end
  resources :answers
  resources :questions
  match 'verification/:email_token' => 'sessions#verification' 
  # resources :answers
  # root :to => "enquetes#index"
  root :to => "welcome#index"
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  def index
    @responses = Response.all
  end

  def new
    # raise params.inspect
    @survey = Enquete.find_by_id(params[:enquete_id])
    @response = Response.find_by_enquete_id_and_user_id(@survey.id, current_user.id)
    if @response
      # puts 2323333333333333333
      flash[:notice] = "Survey answered! Please choose another survey."
      redirect_to enquete_response_path(@survey, @response)
    else
      @response = @survey.responses.build
        # raise @survey.questions.size.inspect
      @survey.questions.size.times {@response.answers.build}
    end
  end

  def create
  	@survey = Enquete.find_by_id(params[:enquete_id])
    @response = Response.new(params[:response])
    @response.user = current_user
    if @response.save
    # raise @response.inspect
      redirect_to enquete_response_path(@survey, @response), notice: 'Thank you for taking the survey.'
    else
      render action: "new"
    end
  end


  def show
    @response = Response.find_by_id(params[:id])
    @survey = @response.enquete
  end


  def edit
    @response = Response.find_by_id(params[:id])
  end

  def update
    @response = Response.find_by_id(params[:id])
    if @response.update_attributes(params[:response])
      redirect_to @response, notice: 'Response updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @response = Response.find(params[:id])
    @response.destroy
    redirect_to enquete_responses_url(@survey.id)
		# redirect_to responses_url
  end
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/_form.html.erb
<p>
  <b>Name:</b>
  <%= @survey.title %>
</p>

<p>
  <b>Description:</b>
  <%= @survey.description %>
</p>

<%= nested_form_for @response, :url => enquete_responses_path do |f| %>
  <% if @response.errors.any? %>
    <div>
      <h2><%= pluralize(@response.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @response.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.hidden_field :enquete_id, :value => @survey.id %>
  <div>
    <b><p>Questions</p></b>

    <% i = 0 %>
    <%= f.fields_for :answers do |a| %>
    
      <div>
        <%= @survey.questions[i].content %>:
        <% if @survey.questions[i].type == 'NumericQuestion' %>
          <%= a.text_field :content, :class => "numeric_field" %>
        <% elsif @survey.questions[i].type == 'DateQuestion' %>
          <%= a.text_field :content, :class => 'date_field' %>
        <% else %>
          <%= a.text_area :content %>
        <% end %>
        <%= a.hidden_field :question_id, :value => @survey.questions[i].id %>
      </div>
      <% i+= 1 %>
    <% end %>
  </div>

  <div>
    <%= f.submit "Submit answers"%>
  </div>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/responses/index.html.erb
<h1>Listing Answers</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @responses.each do |response| %>
  <tr>
    <td><%= link_to 'Show', response %></td>
    <td><%= link_to 'Edit', edit_response_path(response) %></td>
    <td><%= link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Response', new_enquete_response_path %>

app/views/responses/new.html.erb
<h1>Answer</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/responses/show.html.erb
<h2><%=  @response.enquete.title %></h2>
<div>
	<p><%=  @response.enquete.description %></p>
</div>

<table>
	<tr>
		<th>Question</th>
		<th> Answers</th>
	</tr>
	<%  @response.answers.each do  |r| %>
		<tr>
			<td><%= r.question.content %></td>
			<td><%= r.content %></td>
		</tr>
	<% end %>
</table>

<%= link_to 'Back', root_path %>