config/routes.rb
Survey::Application.routes.draw do
  get "sessions/new"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions
  resources :enquetes do
    resources :responses
  end
  resources :answers
  resources :questions
  match 'verification/:email_token' => 'sessions#verification' 
  # resources :answers
  # root :to => "enquetes#index"
  root :to => "welcome#index"
end

app/models/enquete.rb
class Enquete < ActiveRecord::Base
	attr_accessible :title, :description, :questions_attributes
	has_many :questions, :dependent => :destroy
  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
  has_many :essay_questions, :dependent => :destroy
  has_many :numeric_questions, :dependent => :destroy
  has_many :date_questions, :dependent => :destroy
  has_many :responses, :dependent => :destroy

  def self.get_all_published_surveys
  	find_all_by_published true
  end

end

app/controllers/enquetes_controller.rb
class EnquetesController < ApplicationController
  before_filter :admin_login
	def index
    @surveys = Enquete.all()

    respond_to do |format|
      format.html
      format.json { render json: @surveys }
    end
  end

  def show
    @survey = Enquete.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @survey }
    end
  end

  def new
    @survey = Enquete.new
    @questions = Question.types
    3.times {@survey.questions.build}
    respond_to do |format|
      format.html
      format.json { render json: @survey }
    end
  end


  def edit
    @survey = Enquete.find(params[:id])
    @questions = Question.types
  end

  def create
    @questions = Question.types
    @survey = Enquete.new(params[:enquete])
    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @questions = Question.types
    @survey = Enquete.find(params[:id])
    respond_to do |format|
      if @survey.update_attributes(params[:enquete])
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @survey = Enquete.find(params[:id])
    @survey.destroy
    redirect_to enquetes_url
  end
end

app/helpers/enquetes_helper.rb
module EnquetesHelper
end

app/views/enquetes/_form.html.erb
<%= nested_form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div><br/>
  <div>
    <%= f.label :description %><br/>
    <%= f.text_area :description, :rows => 2 %>
  </div>
  <div>
    <%= f.fields_for :questions do |builder| %>
      <%= render "question_fields", :f => builder %>
    <% end %>
  </div>
  <p><%= f.link_to_add "Add a question", :questions %></p>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/enquetes/_question_fields.html.erb
<p>
  <b><%= f.label :content, "Question" %></b><br />
  <%= f.select(:type, @questions) %><br/>
 	<%= f.text_area :content, :rows => 3 %><br/>
  <%= f.link_to_remove "Remove this question" %>
</p>

app/views/enquetes/edit.html.erb
<h1>Editing survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', enquetes_path %>

app/views/enquetes/index.html.erb
<h1>Surveys</h1>

<table>
  <tr>
    <th></th>
    <th>Available surveys</th>
    <th>Description</th>
    <th>Actions</th>
    <th></th>
    <th></th>
  </tr>

<% @surveys.each do |survey| %>
  <tr>
    <td><%= survey.id %></td>
    <td><%=link_to survey.title, enquete_path(survey) %></td>
    <td><%= truncate(survey.description, :length => 40, :separator => '...') %></td>
    <!-- <td><%#= link_to 'Edit', edit_enquete_path(survey) %></td> -->
    <!-- <td><%#= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Create Survey', new_enquete_path %>

app/views/enquetes/new.html.erb
<h1>New survey</h1>

<%= render 'form' %>

<%= link_to 'Back', enquetes_path %>

app/views/enquetes/show.html.erb
<p>
  <b>Name:</b>
  <%= @survey.title %>
</p>

<p>
  <b>Description:</b>
  <%= @survey.description %>
</p>
<hr>

<h2>Responses</h2>
<table>
  <tr>
    <th>From - Email</th>
    <% @survey.questions.each do |question| %>
      <th><%= question.content %></th>
    <% end %>
  </tr>
  <% @survey.responses.each do |response| %>  
    <tr>
      <td><%= response.user.email %></td>
      <% response.answers.each do |answer| %>
        <td><%= answer.content %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<hr>



<%= link_to 'Edit', edit_enquete_path(@survey) %> |
<%= link_to 'Back', enquetes_path %>